- name: install python-pip
  apt: name=python-pip state=present update_cache=yes
  become: True
- name: install git
  apt: name=git state=present update_cache=yes
  become: True
- name: install docker-py
  pip: name=docker-py
  become: True 
