- name: Docker Image Build and push it to a public Repository
  hosts: docker-build
  gather_facts: false
#  connection: local
  vars_prompt:
    - name: "tag_name"
      prompt: "Enter docker image tag number"
      default: "latest"
      private: no
    - name: "action_name"
      prompt: "Enter kubeclt action name"
      default: "update"
      private: no   
  roles:      
    - dependency
    - git
    - docker-build
    - kubernetes-deployment
