- name: Docker Image Build and push it to a public Repository
  hosts: docker-build
  gather_facts: false
  vars_prompt:
    - name: "tag_name"
      prompt: "Enter docker image tag number"
      default: "latest"
      private: no
    - name: "action_name"
      prompt: "Enter kubeclt action name"
      default: "replace"
      private: no
    - name: "git_branch"
      prompt: "Enter your desire git branch name."
      default: "master"
      private: no    
  roles:      
    - dependency
    - git
    - docker-build
    - kubernetes-deployment
