- name: generate namespace
  template: src=namespace.yml.j2 dest=~/namespace.yml
  when: action_name  == "create"

- name: create namespace
  shell: cd ~/;kubectl {{ action_name }} -f namespace.yml
  when: action_name == "create"

- name: copy secret script
  template: src=secret.yml.j2 dest=~/secret.yml
  when: action_name  == "create"

- name: create secret for database
  shell: cd ~/;kubectl {{ action_name }} -f secret.yml
  when: action_name == "create"

- name: copy frontend-svc 
  template: src=frontend-svc.yml.j2 dest=~/frontend-svc.yml
  when: action_name == "create"

- name: create frontend-svc for frontend
  shell: cd ~/;kubectl {{ action_name }} -f frontend-svc.yml
  when: action_name == "create"

- name: copy frontend deployment
  template: src=frontend.yml.j2 dest=~/frontend.yml

- name: deploy frontend using kubectl
  shell: cd ~/;kubectl {{ action_name }} -f frontend.yml

- name: copy backend-svc 
  template: src=backend-svc.yml.j2 dest=~/backend-svc.yml
  when: action_name == "create"

- name: create backend-svc for backend
  shell: cd ~/;kubectl {{ action_name }} -f backend-svc.yml
  when: action_name == "create"  

- name: copy backend deployment
  template: src=backend.yml.j2 dest=~/backend.yml
  
- name: deploy frontend using kubectl
  shell: cd ~/;kubectl {{ action_name }} -f backend.yml



